apiVersion: v1
kind: Secret
metadata:
  name: twitter-credentials
type: Opaque
stringData:
  twitter.properties: |
    twitter-source.token=<token>
    twitter-source.tokenSecret=<token_secret>
    twitter-source.consumerKey=<consumer_key>
    twitter-source.consumerSecret=<consumer_secret>