apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Matthew\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    nodePort: 30601
    targetPort: 5601
  selector:
    io.kompose.service: kibana
