apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Matthew\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: jobmanager
  name: jobmanager
spec:
  type: NodePort
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: ui
    port: 8081
  selector:
    io.kompose.service: jobmanager

